version: "2.3"

networks:
  default:
    external:
      name: ros-network

services:

  web-control:
    #build: ./image
    image: wn1980/web-control-ros${TAG}
    container_name: ros_web_control
    init: true
    restart: unless-stopped
    environment:
      - ROS_MASTER_URI=http://master:11311   
    ports:
      - "4004:8080"
